project_id = "yoxewklaybougzpmzvkg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.reddit-link-bot]
    verify_jwt = false
  [functions.report-episode-duration]
    verify_jwt = false
  [functions.mp3-duration-probe]
    verify_jwt = false
