// Auto-generated few-shot pairs from /mnt/documents/clean_text_gold_filled.xlsx (12 of 60 gold rows).
// Selected 4 from each of yt_dominant / over_trimmed_v3 / sponsor_heavy.
export type FewShot = { bucket: string; raw: string; gold: string };
export const AI_TRIM_FEW_SHOTS: FewShot[] = [
  { bucket: "yt_dominant", raw: `Ebben a solo epizódban a "main character enery"-ről mesélek elsősorban Georgie Stevenson: Prada coffee cups & being that girl című podcast epizódja alapján🎧 Hogyan romantizáld az életed? Nárcisztikusnak számítasz, ha főszereplőnek tekinted önmagad? Csak egyféleképpen lehet ezt csinálni? Tarts velem, és derítsd ki mindezt!😌 ☕️ Támogasd a podcastet: https://www.buymeacoffee.com/abrightplace Ez az epizód YouTube-on is elérhető, itt tudod megtekinteni: https://www.youtube.com/channel/UCCHVBZliKuI3aguExfWWfGg Köszönöm, ha a feliratkozásoddal ott is támogatsz!❤️`, gold: `Ebben a solo epizódban a "main character energy"-ről mesélek nektek, Georgie Stevenson: Prada coffee cups & being that girl című podcast epizódja alapján.` },
  { bucket: "yt_dominant", raw: `A Zsidó Kiválóságok Háza jó alapot adott arra, hogy 3000 évet visszautazzunk az időben és a ma is moder ókori oktatási-vallási szemléletet et elemezzük. Aztán napjaink valósága is ránk köszönt, hiszen a háborúba induló unoka előző napi üzenete is eljutott hozzánk. A zsidóságról, a tehetségről, a tanulás és a józanság fontosságáról egyaránt súlyos, elgondolkodtató mondatok hangzottak el beszélgetésünkben.Témáink:18:00 Holokauszt nélkül beszéni a zsidókról19:40 Opera Füreden a Metropolitanból 21:30 Kedvenc zsidóim24:10 Közoktatási program a világon egyedülállóan Magyarországon26:40 Hajszárító-effektus27:12 EU-s projekt ellenállással28:13 Unoka a háborúban`, gold: `A Zsidó Kiválóságok Háza jó alapot adott arra, hogy 3000 évet visszautazzunk az időben és a ma is moder ókori oktatási-vallási szemléletet et elemezzük. Aztán napjaink valósága is ránk köszönt, hiszen a háborúba induló unoka előző napi üzenete is eljutott hozzánk. A zsidóságról, a tehetségről, a tanulás és a józanság fontosságáról egyaránt súlyos, elgondolkodtató mondatok hangzottak el beszélgetésünkben.Témáink:18:00 Holokauszt nélkül beszéni a zsidókról19:40 Opera Füreden a Metropolitanból 21:30 Kedvenc zsidóim24:10 Közoktatási program a világon egyedülállóan Magyarországon26:40 Hajszárító-effektus27:12 EU-s projekt ellenállással28:13 Unoka a háborúban` },
  { bucket: "yt_dominant", raw: `Milánó két csodálatos csapatának két címlapunkon szereplő csodálatos férfiemberét is méltattuk, de jutott a dicséretből a Juventusnak, a Romának és az Atalantának is. A Napoliról ellenben nem tudtunk ennyire pozitívan beszélni. Jutott idő az európai kupák alapszakaszának zárására és a Laziónál kialakult konfliktusra is. Ez csak egy adásrészlet, ha kíváncsi vagy a teljes epizódra már a megjelenés napján, látogass el támogatói oldalunkra. Támogatói oldalunk: https://www.donably.com/nem-futball-calcio Iratkozz fel YouTube-csatornánkra! https://www.youtube.com/@nemfutballcalcio Hallgass minket a Spotify-on: https://open.spotify.com/show/0ndhw0CPzlNh54dYHJhE2M Facebook-oldal: https://www.facebook.com/@ilnostrocalcio Instagram: https://www.instagram.com/nemfutballcalcio01/ TikTok: https://www.tiktok.com/@nemfutballcalcio (0:00) Zárul a BL alapszakasza (22:32) Deloitte Money League (27:52) A Roma az El-ben és a Milan ellen (35:29) Magic Mike (39:40) Vissza a Romához (47:55) Összeállt az Atalanta (50:32) Minden(ki) a helyén a Juventusnál? (1:04:43) Fantasztikus Fede és az Inter (1:15:00) Sarri és Lotito konfliktusa (1:20:35) Hektikus Genoa-Bologna meccs (1:25:14) Tippjáték és fantasy`, gold: `Milánó két csodálatos csapatának két címlapunkon szereplő csodálatos férfiemberét is méltattuk, de jutott a dicséretből a Juventusnak, a Romának és az Atalantának is. A Napoliról ellenben nem tudtunk ennyire pozitívan beszélni. Jutott idő az európai kupák alapszakaszának zárására és a Laziónál kialakult konfliktusra is.` },
  { bucket: "yt_dominant", raw: `Támogasd a munkánkat és segíts, hogy folytathassuk, bővülhessünk! 🥦 http://paypal.me/csakhaerdekel 🥦 http://patreon.com/csakhaerdekel Milyen hibákat követünk el az étrendünkben? Hogyan áll ma a dietetika az elhízáshoz? Miért nincs értelme tiltólistára tenni ételeket? Hogyan tud együtt dolgozni egy pszichológus és egy dietetikus? Mit tudunk házilag is elkészíteni, és mit nem érdemes? Kakaós csiga? Zserbó? Kovászolt kenyér? Mit gondoljunk ezekről? Értelmezhető-e egy dietetikus számára Norbi működése? (Nem...) De ami még fontosabb: mit gondolunk a body positivity mozgalomról? Hol csúszott félre, hol volt igaza, miért nem sikerült akár az evészavarok, akár az elhízás mértékét csökkenteni a világban? Mi kellene egy jobban működő egészségügyhöz? Hogyan kellene szakemberként kommunikálni, és mit kellene az átlagos laikusoknak elhinni? Túltoltuk vajon az evésről való kommunikációt? Hogyan igazodjunk el a zajban? Szabó Adrienn jelenleg az egyik legnépszerűbb és leghitelesebb dietetikus, aki nem csak magas színvonalon műveli a szakmáját, hanem kommunikációjában is legalább annyira tűpontos, amennyire érzékeny. Megtisztelő volt egyenrangúként beszélgetni vele és ütköztetni a pszichológiai álláspontot az ő dietetikai meglátásaival. Így kell(ene) kinéznie két szakember beszélgetésének, akik közös célokért, de más háttérrel és más véleménnyel érkeznek meg egy társalgásba. Szabó Adrienn oktat…`, gold: `Milyen hibákat követünk el az étrendünkben? Hogyan áll ma a dietetika az elhízáshoz? Miért nincs értelme tiltólistára tenni ételeket? Hogyan tud együtt dolgozni egy pszichológus és egy dietetikus? Mit tudunk házilag is elkészíteni, és mit nem érdemes? Kakaós csiga? Zserbó? Kovászolt kenyér? Mit gondoljunk ezekről? Értelmezhető-e egy dietetikus számára Norbi működése? (Nem...) De ami még fontosabb: mit gondolunk a body positivity mozgalomról? Hol csúszott félre, hol volt igaza, miért nem sikerült akár az evészavarok, akár az elhízás mértékét csökkenteni a világban? Mi kellene egy jobban működő egészségügyhöz? Hogyan kellene szakemberként kommunikálni, és mit kellene az átlagos laikusoknak elhinni? Túltoltuk vajon az evésről való kommunikációt? Hogyan igazodjunk el a zajban? Szabó Adrienn je…` },
  { bucket: "over_trimmed_v3", raw: `<p>A podcastban a 18. heti hétvégi box office eredményekről van szó, és a 19. heti magyar mozis premiemekről.</p>
<p>Timeline:</p>
<p>01:00 Usa Box Office - 18. heti hétvége</p>
<p>18:19 Magyar nézettség - 18. heti hétvége </p>
<p>26:25 Mozis bemutatók - 19. hét</p>
<p>Kapcsolat:</p>
<p>filmhetpodcast@gmail.com</p>
<p>Twitter: @FFilmhet70792</p>
<p>Források:</p>
<p>Box office:</p>
<p><a href="https://filmforgalmazok.hu/">`, gold: `A podcastban a 18. heti hétvégi box office eredményekről van szó, és a 19. heti magyar mozis premiemekről. Timeline: 01:00 Usa Box Office - 18. heti hétvége 18:19 Magyar nézettség - 18. heti hétvége 26:25 Mozis bemutatók - 19. hét` },
  { bucket: "over_trimmed_v3", raw: `Iratkozz fel a csatornámra, hogy ne maradj le a videóimról!&nbsp; → http://bit.ly/FemmeFactoryYT&nbsp; Kövess!&nbsp; » Blog → https://www.femmefactory.hu » Facebook → https://www.facebook.com/femmefactory.hu » Instagram → https://www.instagram.com/femmefactory.hu&nbsp; Zsófival, a Mosoly fitness megalapítójával és vezető edzőjével beszélgettem arról, hogy mennyire fontos és jó a sportolás, nem csak a testnek, de a léleknek is. Kisgyermekes anyaként is nagy szükségünk van a testünk edzésére az állóképességhez, a deformitások elkerüléséhez, a stressz oldásához, a fejünk kitisztításához, a szellemi pihenéshez, feltöltődéshez - illetve a szociális kapcsolatokra, amikhez szintén juthatunk a sportolás, a közösség által. Úgyhogy offline vagy online - edzeni jó és fontos, fogadjátok szeretettel. &nbsp;&nbsp; A Mosoly fitness elérhetőségei:&nbsp; https://www.mosolyfitness.hu/&nbsp; https://www.facebook.com/MOSOLYFITNESS/&nbsp; https://www.instagram.com/mosolyfitnessstudio/&nbsp; https://www.instagram.com/fezsofitt/`, gold: `Zsófival, a Mosoly fitness megalapítójával és vezető edzőjével beszélgettem arról, hogy mennyire fontos és jó a sportolás, nem csak a testnek, de a léleknek is. Kisgyermekes anyaként is nagy szükségünk van a testünk edzésére az állóképességhez, a deformitások elkerüléséhez, a stressz oldásához, a fejünk kitisztításához, a szellemi pihenéshez, feltöltődéshez - illetve a szociális kapcsolatokra, amikhez szintén juthatunk a sportolás, a közösség által. Úgyhogy offline vagy online - edzeni jó és fontos, fogadjátok szeretettel.` },
  { bucket: "over_trimmed_v3", raw: `<p>Az amerikai kormányzati leállás még nem ért véget, de a piacok máris ünneplik az első megállapodást. Nagy a remény, hogy a további két akadályt is sikerül leküzdeni,ami a shutdown végét jelentené. </p><p>——————</p><p><a href="https://pfspartners.hu/divanybeszelgetes-a-tokepiacrol/%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%20%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81%A0%E2%81…`, gold: `Az amerikai kormányzati leállás még nem ért véget, de a piacok máris ünneplik az első megállapodást. Nagy a remény, hogy a további két akadályt is sikerül leküzdeni,ami a shutdown végét jelentené.` },
  { bucket: "over_trimmed_v3", raw: `<p>Ahogy azt már hagyománynak tekinthetjük, január elején most is megdumáljuk Onozó Robival, hogy miért volt jó és miért volt nem annyira jó filmőrültnek lenni tavaly.</p>
<p>Ezek a témák jöttek szóba:</p>
<ul>
 <li>00:00 - Beköszönés, bájolgás</li>
 <li>01:21 - Alig nézik a magyar filmeket a mozikban, de meglepetéssiker a <em>Larry</em>. Tanulságos hollywoodi bukták tavaly.</li>
  <li>16:26 - Streamingen debütáló filmek: <em>Causeway</em>, <em>Cha-Cha Real Smooth</em>, <em>Bardo</em>, <em>Fehér zaj</em>, <em>Az üveghagyma</em>.</li>
  <li>27:08 - <em>Blonde</em>. A Sight and Sound <a href="https://www.bfi.org.uk/sight-and-sound/interviews/im-not-interested-reality-im-interested-images-andrew-dominik-blonde"><strong>Andrew Dominik-interjúja</strong></a> és a hozzá kapcsolódó <a href="https://twitter.com/christinalefou/status/1574785874277064706"><strong>kimaradt jelenet</strong></a>.</li>
  <li>33:18 - Filmes díjak a Covid után.</li>
  <li>37:45 - Nyomorpornó: <em>A bálna</em>, <em>Közel</em>.</li>
  <li>47:15 - Lena Dunham két filmmel tért vissza: <em>Sharp Stick</em>, <em>Catherine Called Birdy</em>.</li>
  <li>56:44 - <em>Aranybulla</em>, <em>A Király</em>.</li>
  <li>1:00:56 - A Sight and Sound <a href="https://www.bfi.org.uk/sight-and-sound/greatest-films-all-time"><strong>minden idők legjobb filmjei</strong></a> listája.</li>
  <li>1:14:05 - Tíz év múlva vajon melyik 2022…`, gold: `Ahogy azt már hagyománynak tekinthetjük, január elején most is megdumáljuk Onozó Robival, hogy miért volt jó és miért volt nem annyira jó filmőrültnek lenni tavaly. Ezek a témák jöttek szóba:  •  00:00 - Beköszönés, bájolgás   01:21 - Alig nézik a magyar filmeket a mozikban, de meglepetéssiker a Larry. Tanulságos hollywoodi bukták tavaly.   •  16:26 - Streamingen debütáló filmek: Causeway, Cha-Cha Real Smooth, Bardo, Fehér zaj, Az üveghagyma.   •  27:08 - Blonde. A Sight and Sound Andrew Dominik-interjúja (https://www.bfi.org.uk/sight-and-sound/interviews/im-not-interested-reality-im-interested-images-andrew-dominik-blonde)  és a hozzá kapcsolódó kimaradt jelenet (https://twitter.com/christinalefou/status/1574785874277064706) .  •  33:18 - Filmes díjak a Covid után.   •  37:45 - Nyomorporn…` },
  { bucket: "sponsor_heavy", raw: `Biztonságos-e mozogni a terhesség alatt? - Milyen mozgásformák ajánlottak kismamáknak? - Mennyit mozoghat egy kismama adott trimeszterben?Vannak - tiltólistás mozgásformák? - Milyen jelekre kell figyelni mozgás közben? - Miért fontos a gátizomtorna a terhesség alatt? - Mikor kezdhetem el a mozgást szülés után? - Mit kell tudni a hegmasszázsról? - Mit tehetek, ha császár után természetes úton szeretnék újra szülni? - Fáradt vagyok, akkor is jót tesz a mozgás? Szakértőnk: Gedeon Fruzsina Virág, Fitmummy® Posztnatális tréner, gyógytornász-fizioterapeuta #hellobabypodcast #hellobabytop10 #vaspótlás #vashiány #vashiánytünetei #terhességalattimozgás #vashiányvárandósság #podcast #hellobabymagazin Weboldal: https://hellobaby.hu/ Webshop: https://hellobaby.hu/webshop/ Facebook: https://www.facebook.com/HelloBaby.magazin Instagram: https://www.instagram.com/hellobabymagazin/ TikTok: https://www.tiktok.com/@hellobabymagazin`, gold: `Biztonságos-e mozogni a terhesség alatt? - Milyen mozgásformák ajánlottak kismamáknak? - Mennyit mozoghat egy kismama adott trimeszterben?Vannak - tiltólistás mozgásformák? - Milyen jelekre kell figyelni mozgás közben? - Miért fontos a gátizomtorna a terhesség alatt? - Mikor kezdhetem el a mozgást szülés után? - Mit kell tudni a hegmasszázsról? - Mit tehetek, ha császár után természetes úton szeretnék újra szülni? - Fáradt vagyok, akkor is jót tesz a mozgás? Szakértőnk: Gedeon Fruzsina Virág, Fitmummy® Posztnatális tréner, gyógytornász-fizioterapeuta #hellobabypodcast #hellobabytop10 #vaspótlás #vashiány #vashiánytünetei #terhességalattimozgás #vashiányvárandósság #podcast #hellobabymagazin` },
  { bucket: "sponsor_heavy", raw: `#hirdetés
Minden döntésünk alakítja a jövőt. Ahogy mi gyűjtünk, úgy épül egy fenntarthatóbb ország. Az adást a MOHU támogatta. 
A munkáról, a hozzá való viszonyról, ennek a viszonynak megváltoztatásáról esik szó a zCast friss adásában. Milyen régóta van velünk a mai értelemben vett munka, hogyan működtek előtte az emberek és a közösségek, miként távolított el a természettől, és mi okozza, hogy állandóan rohanunk magunk után, és semmire nem jut idő? És hogy kapcsolódik mindehhez Jane Goodall, az irokézek és a hét generációs gondolkodás?
Hogyan tudunk a 21. századi polikrízis kihívásaira megoldásokat keresni, tenni például a természetért, miközben pörgetjük a napi 8 órás mókuskereket, és nem érjük utol magunkat. Ilyen és hasonló kérdésre keresi a választ Michaletzky Luca ökológiai szemléletű pszichológussal és Rimóczi Oszkárral, a Mégis Kollektíva alapítójával a zCast munkáról szóló adásában a HVG fenntarthatósági podcastjának házigazdája, Fait Federika. Kiderül többek között, milyen régen van velünk a munka, hol tévedtünk el a hozzá való viszonyunkban, milyen messzire tekintsünk vissza a jó gyakorlatokért, és mennyire előre, amikor a jövőről döntünk? 
💌 Iratkozz fel a hírleveleinkre: https://bit.ly/hvg-hirlevelek
📍 Itt is megtalálsz minket:
🔗 Weboldal: https://bit.ly/hvg-webpage
🤝 Támogass minket: https://tamogatas.hvg.hu/
🎟️ Klub360: info.hvg.hu/klub360
💳 HVG Klubkártya: https:…`, gold: `A munkáról, a hozzá való viszonyról, ennek a viszonynak megváltoztatásáról esik szó a zCast friss adásában. Milyen régóta van velünk a mai értelemben vett munka, hogyan működtek előtte az emberek és a közösségek, miként távolított el a természettől, és mi okozza, hogy állandóan rohanunk magunk után, és semmire nem jut idő? És hogy kapcsolódik mindehhez Jane Goodall, az irokézek és a hét generációs gondolkodás? Hogyan tudunk a 21. századi polikrízis kihívásaira megoldásokat keresni, tenni például a természetért, miközben pörgetjük a napi 8 órás mókuskereket, és nem érjük utol magunkat. Ilyen és hasonló kérdésre keresi a választ Michaletzky Luca ökológiai szemléletű pszichológussal és Rimóczi Oszkárral, a Mégis Kollektíva alapítójával a zCast munkáról szóló adásában a HVG fenntarthatósági po…` },
  { bucket: "sponsor_heavy", raw: `🐕 🛜 Nincs a közeledben Tükör Módszeres iskola? Vagy otthon dolgoznál a kutyusoddal? Az online tanfolyamainkat pont neked találtuk ki: Kölyökkutyáknak:https://bit.ly/kolyokonline Kamasz és felnőtt kutyáknak:https://bit.ly/onlinekutya ------------------------------------------------------------------------------- Hogyan szoktassam le a felugrálásról? Zavar, hogy kutyád felugrál? Rád vagy akár másokra is? Próbáltál már mindent, de semmi sem segít tartósan? Lehet, hogy rossz oldalról közelíted meg a problémát! A Neked Ugatok podcast legfrissebb epizódjában a felugrálás és az arról való leszoktatás a témánk. Korom Gábor kulcsmondata, ami megváltoztathatja a kutyádhoz való hozzáállásodat:"Alapvetően az a helyzet, hogy nem arra kell megtanítani a kutyát, szerintem, hogy ne ugráljon fel, hanem arra kell megtanítani a kutyát, hogy ha bármit csinál, és nem akarom, akkor azt ne csinálja tovább." Az adásból kiderül: - Miért az általános kontroll tanítása a kulcs, nem pedig egy-egy viselkedés tüneti kezelése. - A felugrálás valódi mozgatórugói: figyelemkeresés, öröm, tanult viselkedés, frusztráció, bizonytalanság vagy akár dominancia? - Hogyan (és miért NE) tiltsunk specifikus viselkedéseket.- A tiltószó helyes használata és a kutyával való egyértelmű kommunikáció alapjai. - Hogyan kezeljük a frusztrációból vagy bizonytalanságból fakadó felugrálást. - Mikor elfogadható és mikor káros a felu…`, gold: `Hogyan szoktassam le a felugrálásról? Zavar, hogy kutyád felugrál? Rád vagy akár másokra is? Próbáltál már mindent, de semmi sem segít tartósan? Lehet, hogy rossz oldalról közelíted meg a problémát! A Neked Ugatok podcast legfrissebb epizódjában a felugrálás és az arról való leszoktatás a témánk. Korom Gábor kulcsmondata, ami megváltoztathatja a kutyádhoz való hozzáállásodat:"Alapvetően az a helyzet, hogy nem arra kell megtanítani a kutyát, szerintem, hogy ne ugráljon fel, hanem arra kell megtanítani a kutyát, hogy ha bármit csinál, és nem akarom, akkor azt ne csinálja tovább." Az adásból kiderül: - Miért az általános kontroll tanítása a kulcs, nem pedig egy-egy viselkedés tüneti kezelése. - A felugrálás valódi mozgatórugói: figyelemkeresés, öröm, tanult viselkedés, frusztráció, bizonytala…` },
  { bucket: "sponsor_heavy", raw: `<p>Néhány dolog, ami közben felmerült... </p><p>Dávid Giannisról szóló cikke:<br /><a href="https://index.hu/sport/kosarlabda/2017/01/10/giannis_antetokounmpo/ ">https://index.hu/sport/kosarlabda/2017/01/10/giannis_antetokounmpo/ </a></p><p>Nostalgia Critic - Space Jam:<br /><a href="https://www.youtube.com/watch?v=K5vu9kUqc2U&t=0s">https://youtu.be/K5vu9kUqc2U</a> </p><p>Pisilős app: <br /><a href="https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbjVEVmlzclRnMmtnSXpqdTRBYVdjU2ZTY2VZUXxBQ3Jtc0trel9NbUkxd2ZSNlZhbGs4MXNPTGhYbUZqSWVmWlhQV1VkcEIzT0JKSlllWkxJU0w0MDc5OUhWQS14TkNpeV9xMDc2Vng2UmJYSWx0SEpNa1lIQ2VXTVBYLVBXUTJpeGxMdF9XZDVrTFdpeXl2YjlhWQ&q=https%3A%2F%2Frunpee.com%2F" target="_blank">https://runpee.com/</a> </p><p>Az ESPN reklámja: <br /><a href="https://www.youtube.com/watch?v=Ofp-g-3upz8&t=0s">https://youtu.be/Ofp-g-3upz8</a> </p><p>Space Jam 2 trailer mélyelemzés: <br /><a href="https://www.youtube.com/watch?v=QLXPNONjSHM&t=0s">https://youtu.be/QLXPNONjSHM</a> </p><p>A magyar lány, aki a SPACE JAM 2-N DOLGOZIK! <br /><a href="https://www.youtube.com/watch?v=k5bdy9CeB9s&t=0s">https://youtu.be/k5bdy9CeB9s</a> </p><p>The Shop "kritika": <br /><a href="https://www.youtube.com/watch?v=dmnixiEmusc&t=0s">https://youtu.be/dmnixiEmusc</a> </p><p>Csatlakozz a Team Bazska Patreonhoz: <br /><a href="https://www.youtube.com/redirect?event=video_descriptio…`, gold: `Néhány dolog, ami közben felmerült...  Dávid Giannisról szóló cikke: Nostalgia Critic - Space Jam: Pisilős app: Az ESPN reklámja: Space Jam 2 trailer mélyelemzés: A magyar lány, aki a SPACE JAM 2-N DOLGOZIK! The Shop "kritika":` },
];
