// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-podcasts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
function getSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
function json(obj) {
  return {
    content: [{ type: "text", text: JSON.stringify(obj, null, 2) }],
    structuredContent: obj
  };
}
function err(msg) {
  return { content: [{ type: "text", text: msg }], isError: true };
}

// src/lib/mcp/tools/search-podcasts.ts
var search_podcasts_default = defineTool({
  name: "search_podcasts",
  title: "Podcast keres\xE9s",
  description: "Magyar podcastok keres\xE9se n\xE9v/le\xEDr\xE1s alapj\xE1n a podiverzum.hu katal\xF3gusban. Visszaadja a slug, c\xEDm, kateg\xF3ria, rank \xE9s publikus URL adatokat.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keres\u0151kifejez\xE9s (podcast n\xE9v vagy t\xE9ma)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max tal\xE1latsz\xE1m (alap: 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    try {
      const sb = getSupabase();
      const lim = limit ?? 15;
      const { data, error } = await sb.from("podcasts").select("id, slug, title, description, categories, rank_label, podiverzum_rank, image_url, language").ilike("language", "hu%").eq("rss_status", "active").or(`title.ilike.%${query}%,description.ilike.%${query}%`).order("podiverzum_rank", { ascending: false, nullsFirst: false }).limit(lim);
      if (error) return err(error.message);
      const items = (data || []).map((p) => ({
        ...p,
        url: `https://podiverzum.hu/podcast/${p.slug}`
      }));
      return json({ count: items.length, items });
    } catch (e) {
      return err(e?.message || "unknown error");
    }
  }
});

// src/lib/mcp/tools/get-podcast.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_podcast_default = defineTool2({
  name: "get_podcast",
  title: "Podcast r\xE9szletek",
  description: "Egy podcast teljes adatai slug alapj\xE1n, a legut\xF3bbi 10 epiz\xF3ddal egy\xFCtt.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Podcast slug (pl. 'partizan-podcast').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    try {
      const sb = getSupabase();
      const { data: podcast, error } = await sb.from("podcasts").select("*").eq("slug", slug).maybeSingle();
      if (error) return err(error.message);
      if (!podcast) return err(`Podcast not found: ${slug}`);
      const { data: episodes } = await sb.from("episodes").select("id, slug, title, description, published_at, duration_seconds").eq("podcast_id", podcast.id).order("published_at", { ascending: false }).limit(10);
      return json({
        podcast: { ...podcast, url: `https://podiverzum.hu/podcast/${podcast.slug}` },
        recent_episodes: (episodes || []).map((e) => ({
          ...e,
          url: `https://podiverzum.hu/podcast/${podcast.slug}/${e.slug}`
        }))
      });
    } catch (e) {
      return err(e?.message || "unknown error");
    }
  }
});

// src/lib/mcp/tools/search-episodes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/entityResolve.ts
var PODIVERZUM_ORIGIN = "https://podiverzum.hu";
function clampEvidencePhrase(input, max) {
  if (typeof input !== "string") return void 0;
  const s = input.replace(/\s+/g, " ").trim();
  if (!s) return void 0;
  return s.length <= max ? s : `${s.slice(0, Math.max(0, max - 1)).trimEnd()}\u2026`;
}
function episodeUrl(podcastSlug, episodeSlug) {
  if (!podcastSlug || !episodeSlug) return void 0;
  return `${PODIVERZUM_ORIGIN}/podcast/${podcastSlug}/${episodeSlug}`;
}
function podcastUrl(slug) {
  return slug ? `${PODIVERZUM_ORIGIN}/podcast/${slug}` : void 0;
}
var FORBIDDEN_RESPONSE_KEYS = [
  "chunk_match",
  "content_snippet",
  "transcript",
  "segments",
  "ai_reason",
  "ai_evidence_phrases",
  "editorial_notes",
  "ai_review_summary",
  "source_evidence",
  "understanding",
  "cache_hit",
  "timing"
];
function stripForbidden(value) {
  if (Array.isArray(value)) return value.map((v) => stripForbidden(v));
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      if (FORBIDDEN_RESPONSE_KEYS.includes(k)) continue;
      if (v === void 0) continue;
      out[k] = stripForbidden(v);
    }
    return out;
  }
  return value;
}
function shapeSearchEpisode(e) {
  const podcast = e.podcasts || {};
  const summary = typeof e.ai_summary === "string" && e.ai_summary.trim() ? e.ai_summary : typeof e.summary === "string" && e.summary.trim() ? e.summary : typeof e.description === "string" ? e.description : "";
  return stripForbidden({
    id: e.id,
    title: e.display_title || e.title,
    slug: e.slug,
    published_at: e.published_at,
    summary: clampEvidencePhrase(summary, 600),
    podcast: {
      id: e.podcast_id,
      title: podcast.display_title || podcast.title,
      slug: podcast.slug,
      url: podcastUrl(podcast.slug)
    },
    why_matched: typeof e.why_matched === "string" ? e.why_matched : void 0,
    source_url: episodeUrl(podcast.slug, e.slug)
  });
}

// src/lib/mcp/tools/search-episodes.ts
var search_episodes_default = defineTool3({
  name: "search_episodes",
  title: "Epiz\xF3d keres\xE9s",
  description: "Magyar podcast epiz\xF3dok szemantikus + kulcsszavas keres\xE9se (search-hybrid v13). C\xEDmre, le\xEDr\xE1sra \xE9s tartalomra keres. \xC1tirat-r\xE9szletet nem ad vissza; r\xE9szletes kontextushoz haszn\xE1ld a `get_episode_context` tool-t.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Keres\u0151kifejez\xE9s."),
    limit: z3.number().int().min(1).max(30).optional().describe("Max tal\xE1lat (alap: 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    try {
      const url = process.env.SUPABASE_URL;
      const key = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;
      if (!url || !key) return err("Missing SUPABASE env");
      const lim = limit ?? 10;
      const res = await fetch(`${url}/functions/v1/search-hybrid`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: key,
          Authorization: `Bearer ${key}`
        },
        body: JSON.stringify({ q: query, limit: lim, rerank: false })
      });
      if (!res.ok) return err(`search-hybrid ${res.status}: ${(await res.text()).slice(0, 300)}`);
      const data = await res.json();
      const raw = data?.episodes || data?.items || [];
      const items = raw.slice(0, lim).map((e) => shapeSearchEpisode(e));
      return json(
        stripForbidden({
          count: items.length,
          confidence_band: typeof data?.confidence_band === "string" ? data.confidence_band : void 0,
          semantic: typeof data?.semantic === "boolean" ? data.semantic : void 0,
          engine: typeof data?.engine === "string" ? data.engine : void 0,
          items
        })
      );
    } catch (e) {
      return err(e?.message || "unknown error");
    }
  }
});

// src/lib/mcp/tools/get-toplist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_toplist_default = defineTool4({
  name: "get_toplist",
  title: "Podiverzum toplista",
  description: "A Podiverzum aktu\xE1lis magyar podcast toplist\xE1ja (Apple + Spotify + YouTube f\xFAzi\xF3, RRF-alap\xFA).",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Max tal\xE1latsz\xE1m (alap: 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    try {
      const sb = getSupabase();
      const { data, error } = await sb.rpc("get_trending_podcasts", { p_limit: limit ?? 20 });
      if (error) return err(error.message);
      const items = (data || []).map((p, i) => ({
        rank: i + 1,
        title: p.title,
        slug: p.slug,
        trending_score: p.trending_score,
        source_count: p.source_count,
        best_rank: p.best_rank,
        url: p.slug ? `https://podiverzum.hu/podcast/${p.slug}` : void 0
      }));
      return json({ count: items.length, items });
    } catch (e) {
      return err(e?.message || "unknown error");
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "podiverzum-mcp",
  title: "Podiverzum \u2013 Magyar podcast katal\xF3gus",
  version: "0.1.0",
  instructions: "A podiverzum.hu magyar podcast katal\xF3gus eszk\xF6zei. Haszn\xE1ld a `search_podcasts` \xE9s `search_episodes` tool-okat keres\xE9shez, a `get_podcast` tool-t egy m\u0171sor r\xE9szleteihez slug alapj\xE1n, \xE9s a `get_toplist` tool-t az aktu\xE1lis magyar toplist\xE1hoz.",
  tools: [search_podcasts_default, get_podcast_default, search_episodes_default, get_toplist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
