WITH rows(query, query_type, expected_intent, expected_podcast_slug, expected_entity, must_include, must_exclude, notes, sort_order) AS (
  VALUES
  ($$Friderikusz Podcast$$, $$podcast_name$$, $$topic$$, $$friderikusz-podcast$$, NULL, '["friderikusz"]'::jsonb, '[]'::jsonb, $$Known podcast title should pin the podcast and recent episodes.$$ , 10),
  ($$Partizán$$, $$podcast_name$$, $$topic$$, $$partizan$$, NULL, '["partizán"]'::jsonb, '[]'::jsonb, $$Known podcast title, accent preserved.$$ , 20),
  ($$Partizan podcast$$, $$podcast_name$$, $$topic$$, $$partizan-podcast$$, NULL, '["partizan"]'::jsonb, '[]'::jsonb, $$Known podcast title, no accent.$$ , 30),
  ($$TheVR Happy Hour$$, $$podcast_name$$, $$topic$$, $$thevr-happy-hour$$, NULL, '["thevr"]'::jsonb, '[]'::jsonb, $$Brand-like podcast title.$$ , 40),
  ($$Balázsék$$, $$podcast_name$$, $$topic$$, $$balazsek$$, NULL, '["balázsék"]'::jsonb, '[]'::jsonb, $$Radio show title should resolve directly.$$ , 50),
  ($$Hold After Hours$$, $$podcast_name$$, $$topic$$, $$hold-after-hours$$, NULL, '["hold"]'::jsonb, '[]'::jsonb, $$Finance podcast title should not be interpreted as English hold verb.$$ , 60),
  ($$Portfolio Checklist$$, $$podcast_name$$, $$topic$$, $$portfolio-checklist$$, NULL, '["portfolio"]'::jsonb, '[]'::jsonb, $$Known finance podcast title.$$ , 70),
  ($$Qubit Podcast$$, $$podcast_name$$, $$topic$$, $$qubit-podcast$$, NULL, '["qubit"]'::jsonb, '[]'::jsonb, $$Known science/tech podcast title.$$ , 80),
  ($$Az élet meg minden$$, $$podcast_name$$, $$topic$$, $$az-elet-meg-minden$$, NULL, '["élet"]'::jsonb, '[]'::jsonb, $$Known interview podcast title.$$ , 90),
  ($$Pogi Podcast$$, $$podcast_name$$, $$topic$$, $$pogi-podcast$$, NULL, '["pogi"]'::jsonb, '[]'::jsonb, $$Known public affairs podcast title.$$ , 100),
  ($$Friderikusz Sándor$$, $$person$$, $$person$$, NULL, $$Friderikusz Sándor$$, '["friderikusz"]'::jsonb, '[]'::jsonb, $$Person search should surface episodes about or with Friderikusz.$$ , 210),
  ($$Magyar Péter$$, $$person$$, $$person$$, NULL, $$Magyar Péter$$, '["magyar", "péter"]'::jsonb, '[]'::jsonb, $$Important HU public figure, must not collapse into generic magyar topic.$$ , 220),
  ($$Orbán Viktor$$, $$person$$, $$person$$, NULL, $$Orbán Viktor$$, '["orbán", "viktor"]'::jsonb, '[]'::jsonb, $$Public figure/person intent.$$ , 230),
  ($$Karikó Katalin$$, $$person$$, $$person$$, NULL, $$Karikó Katalin$$, '["karikó"]'::jsonb, '[]'::jsonb, $$Scientist/person search.$$ , 240),
  ($$Máté Gábor trauma$$, $$person_topic$$, $$person$$, NULL, $$Máté Gábor$$, '["trauma"]'::jsonb, '[]'::jsonb, $$Person plus topic should keep both signals.$$ , 250),
  ($$Zsiday Viktor$$, $$person$$, $$person$$, NULL, $$Zsiday Viktor$$, '["zsiday"]'::jsonb, '[]'::jsonb, $$Finance person search.$$ , 260),
  ($$Szabó Magda$$, $$person$$, $$person$$, NULL, $$Szabó Magda$$, '["szabó", "magda"]'::jsonb, '[]'::jsonb, $$Accent-sensitive Hungarian name test.$$ , 270),
  ($$Schmied Andi$$, $$person$$, $$person$$, NULL, $$Schmied Andi$$, '["schmied", "andi"]'::jsonb, '[]'::jsonb, $$Known previous noisy name-query regression.$$ , 280),
  ($$Áder János$$, $$person$$, $$person$$, NULL, $$Áder János$$, '["áder"]'::jsonb, '[]'::jsonb, $$Public figure and podcast host/person.$$ , 290),
  ($$Lilu$$, $$person$$, $$person$$, NULL, $$Lilu$$, '["lilu"]'::jsonb, '[]'::jsonb, $$Single-name public figure / host test.$$ , 300),
  ($$OTP$$, $$company_brand$$, $$ticker$$, NULL, $$OTP Bank$$, '["otp"]'::jsonb, '[]'::jsonb, $$Hungarian ticker/company query.$$ , 410),
  ($$OTP Bank$$, $$company_brand$$, $$company$$, NULL, $$OTP Bank$$, '["otp", "bank"]'::jsonb, '[]'::jsonb, $$Company full-name query.$$ , 420),
  ($$MOL részvény$$, $$company_brand$$, $$ticker$$, NULL, $$MOL$$, '["mol", "részvény"]'::jsonb, '[]'::jsonb, $$Hungarian ticker with stock intent.$$ , 430),
  ($$4iG$$, $$company_brand$$, $$ticker$$, NULL, $$4iG$$, '["4ig"]'::jsonb, '[]'::jsonb, $$Alphanumeric BÉT ticker.$$ , 440),
  ($$Richter Gedeon$$, $$company_brand$$, $$company$$, NULL, $$Richter Gedeon$$, '["richter"]'::jsonb, '[]'::jsonb, $$Hungarian pharma company.$$ , 450),
  ($$Magyar Telekom$$, $$company_brand$$, $$company$$, NULL, $$Magyar Telekom$$, '["telekom"]'::jsonb, '[]'::jsonb, $$Hungarian telco company.$$ , 460),
  ($$Nvidia$$, $$company_brand$$, $$company$$, NULL, $$Nvidia$$, '["nvidia"]'::jsonb, '[]'::jsonb, $$Global tech brand query.$$ , 470),
  ($$NVDA részvény$$, $$company_brand$$, $$ticker$$, NULL, $$Nvidia$$, '["nvda"]'::jsonb, '[]'::jsonb, $$US ticker with Hungarian stock term.$$ , 480),
  ($$Tesla részvény$$, $$company_brand$$, $$ticker$$, NULL, $$Tesla$$, '["tesla"]'::jsonb, '[]'::jsonb, $$US stock brand query.$$ , 490),
  ($$Bitcoin$$, $$company_brand$$, $$ticker$$, NULL, $$Bitcoin$$, '["bitcoin"]'::jsonb, '[]'::jsonb, $$Crypto asset query.$$ , 500),
  ($$Tisza Párt$$, $$politics_entity$$, $$company$$, NULL, $$Tisza Párt$$, '["tisza"]'::jsonb, '[]'::jsonb, $$Political party / organization intent.$$ , 610),
  ($$Fidesz$$, $$politics_entity$$, $$company$$, NULL, $$Fidesz$$, '["fidesz"]'::jsonb, '[]'::jsonb, $$Political party query.$$ , 620),
  ($$DK$$, $$politics_entity$$, $$company$$, NULL, $$Demokratikus Koalíció$$, '["dk"]'::jsonb, '[]'::jsonb, $$Short party acronym query.$$ , 630),
  ($$Mi Hazánk$$, $$politics_entity$$, $$company$$, NULL, $$Mi Hazánk$$, '["hazánk"]'::jsonb, '[]'::jsonb, $$Political party phrase query.$$ , 640),
  ($$Momentum$$, $$politics_entity$$, $$company$$, NULL, $$Momentum$$, '["momentum"]'::jsonb, '[]'::jsonb, $$Party/organization query, also common word risk.$$ , 650),
  ($$Parlament$$, $$politics_topic$$, $$topic$$, NULL, $$Parlament$$, '["parlament"]'::jsonb, '[]'::jsonb, $$Institution/topic query.$$ , 660),
  ($$választás 2026$$, $$politics_topic$$, $$news$$, NULL, NULL, '["választás"]'::jsonb, '[]'::jsonb, $$Future election/news-intent query.$$ , 670),
  ($$ukrajnai háború$$, $$politics_topic$$, $$topic$$, NULL, NULL, '["ukrajna", "háború"]'::jsonb, '[]'::jsonb, $$Geopolitical topic query.$$ , 680),
  ($$orosz irodalom$$, $$topic_disambiguation$$, $$topic$$, NULL, $$orosz irodalom$$, '["irodalom"]'::jsonb, '["orosz ferenc"]'::jsonb, $$Known adjective+noun disambiguation: not a person surname query.$$ , 690),
  ($$magyar gazdaság és infláció$$, $$politics_economy$$, $$topic$$, NULL, NULL, '["gazdaság", "infláció"]'::jsonb, '[]'::jsonb, $$Multi-term economy query.$$ , 700),
  ($$MNB kamatdöntés$$, $$finance_topic$$, $$topic$$, NULL, $$MNB$$, '["kamat"]'::jsonb, '[]'::jsonb, $$Central bank topic query.$$ , 810),
  ($$infláció Magyarországon$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["infláció"]'::jsonb, '[]'::jsonb, $$Macroeconomics topic query.$$ , 820),
  ($$forint árfolyam$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["forint"]'::jsonb, '[]'::jsonb, $$Currency topic query.$$ , 830),
  ($$lakáspiac$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["lakáspiac"]'::jsonb, '[]'::jsonb, $$Real estate/economy topic.$$ , 840),
  ($$állampapír$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["állampapír"]'::jsonb, '[]'::jsonb, $$Retail finance topic.$$ , 850),
  ($$nyugdíj megtakarítás$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["nyugdíj", "megtakarítás"]'::jsonb, '[]'::jsonb, $$Personal finance query.$$ , 860),
  ($$vállalkozás indítás$$, $$business_topic$$, $$topic$$, NULL, NULL, '["vállalkozás"]'::jsonb, '[]'::jsonb, $$Business/life advice query.$$ , 870),
  ($$startup befektetés$$, $$business_topic$$, $$topic$$, NULL, NULL, '["startup", "befektetés"]'::jsonb, '[]'::jsonb, $$Startup/VC topic query.$$ , 880),
  ($$adózás egyéni vállalkozó$$, $$business_topic$$, $$topic$$, NULL, NULL, '["adózás", "vállalkozó"]'::jsonb, '[]'::jsonb, $$Practical business query.$$ , 890),
  ($$ingatlan befektetés$$, $$finance_topic$$, $$topic$$, NULL, NULL, '["ingatlan", "befektetés"]'::jsonb, '[]'::jsonb, $$Investment real-estate query.$$ , 900),
  ($$mesterséges intelligencia$$, $$tech_topic$$, $$topic$$, NULL, NULL, '["mesterséges", "intelligencia"]'::jsonb, '[]'::jsonb, $$Core tech topic query.$$ , 1010),
  ($$AI szabályozás$$, $$tech_topic$$, $$topic$$, NULL, NULL, '["ai", "szabályozás"]'::jsonb, '[]'::jsonb, $$AI governance query.$$ , 1020),
  ($$ChatGPT oktatás$$, $$tech_topic$$, $$topic$$, NULL, $$ChatGPT$$, '["oktatás"]'::jsonb, '[]'::jsonb, $$Product plus education topic.$$ , 1030),
  ($$kiberbiztonság$$, $$tech_topic$$, $$topic$$, NULL, NULL, '["kiberbiztonság"]'::jsonb, '[]'::jsonb, $$Cybersecurity topic.$$ , 1040),
  ($$űrkutatás$$, $$science_topic$$, $$topic$$, NULL, NULL, '["űrkutatás"]'::jsonb, '[]'::jsonb, $$Science topic.$$ , 1050),
  ($$rákkutatás$$, $$science_topic$$, $$topic$$, NULL, NULL, '["rákkutatás"]'::jsonb, '[]'::jsonb, $$Medical science topic.$$ , 1060),
  ($$klímaváltozás$$, $$science_topic$$, $$topic$$, NULL, NULL, '["klíma"]'::jsonb, '[]'::jsonb, $$Climate topic.$$ , 1070),
  ($$energiaárak$$, $$science_economy_topic$$, $$topic$$, NULL, NULL, '["energia"]'::jsonb, '[]'::jsonb, $$Energy/economy topic.$$ , 1080),
  ($$elektromos autó$$, $$tech_topic$$, $$topic$$, NULL, NULL, '["elektromos", "autó"]'::jsonb, '[]'::jsonb, $$EV topic.$$ , 1090),
  ($$adatközpontok energiafogyasztása$$, $$tech_topic$$, $$topic$$, NULL, NULL, '["adatközpont", "energia"]'::jsonb, '[]'::jsonb, $$Longer tech/economy query.$$ , 1100),
  ($$trauma feldolgozása$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["trauma"]'::jsonb, '[]'::jsonb, $$Psychology/self-help topic.$$ , 1210),
  ($$szorongás kezelése$$, $$health_life_topic$$, $$question$$, NULL, NULL, '["szorongás"]'::jsonb, '[]'::jsonb, $$Mental health question-like query.$$ , 1220),
  ($$kiégés munkahely$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["kiégés"]'::jsonb, '[]'::jsonb, $$Workplace mental-health topic.$$ , 1230),
  ($$alvás gyerek$$, $$health_life_topic$$, $$question$$, NULL, NULL, '["alvás", "gyerek"]'::jsonb, '[]'::jsonb, $$Parenting/sleep query.$$ , 1240),
  ($$válás gyerekekkel$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["válás", "gyerek"]'::jsonb, '[]'::jsonb, $$Family topic query.$$ , 1250),
  ($$párkapcsolati konfliktus$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["párkapcsolat"]'::jsonb, '[]'::jsonb, $$Relationship topic query.$$ , 1260),
  ($$ADHD felnőttkorban$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["adhd"]'::jsonb, '[]'::jsonb, $$Health/personality topic query.$$ , 1270),
  ($$autizmus$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["autizmus"]'::jsonb, '[]'::jsonb, $$Neurodiversity topic query.$$ , 1280),
  ($$fogyás inzulinrezisztencia$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["fogyás", "inzulinrezisztencia"]'::jsonb, '[]'::jsonb, $$Nutrition/metabolic health query.$$ , 1290),
  ($$futás kezdőknek$$, $$health_life_topic$$, $$topic$$, NULL, NULL, '["futás"]'::jsonb, '[]'::jsonb, $$Fitness practical query.$$ , 1300),
  ($$true crime magyar$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["true crime"]'::jsonb, '[]'::jsonb, $$Genre search query.$$ , 1410),
  ($$történelem podcast$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["történelem"]'::jsonb, '[]'::jsonb, $$Category/topic query.$$ , 1420),
  ($$hidegháború$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["hidegháború"]'::jsonb, '[]'::jsonb, $$History topic query.$$ , 1430),
  ($$második világháború$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["világháború"]'::jsonb, '[]'::jsonb, $$History topic query.$$ , 1440),
  ($$kortárs irodalom$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["irodalom"]'::jsonb, '[]'::jsonb, $$Literature topic query.$$ , 1450),
  ($$film kritika$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["film"]'::jsonb, '[]'::jsonb, $$Film culture topic.$$ , 1460),
  ($$zeneipar$$, $$culture_topic$$, $$topic$$, NULL, NULL, '["zeneipar"]'::jsonb, '[]'::jsonb, $$Music industry topic.$$ , 1470),
  ($$foci válogatott$$, $$sport_topic$$, $$topic$$, NULL, NULL, '["foci", "válogatott"]'::jsonb, '[]'::jsonb, $$Sport topic query.$$ , 1480),
  ($$Forma 1$$, $$sport_topic$$, $$topic$$, NULL, NULL, '["forma", "1"]'::jsonb, '[]'::jsonb, $$F1 alias handling.$$ , 1490),
  ($$NBA magyarul$$, $$sport_topic$$, $$topic$$, NULL, $$NBA$$, '["nba"]'::jsonb, '[]'::jsonb, $$Sports league query.$$ , 1500),
  ($$mit hallgassak vezetés közben$$, $$mood_situation$$, $$question$$, NULL, NULL, '["vezetés"]'::jsonb, '[]'::jsonb, $$Situation-based discovery, Netflix-like query.$$ , 1610),
  ($$könnyed beszélgetés estére$$, $$mood_situation$$, $$topic$$, NULL, NULL, '["könnyed"]'::jsonb, '[]'::jsonb, $$Mood-based discovery.$$ , 1620),
  ($$okos podcast reggeli kávéhoz$$, $$mood_situation$$, $$topic$$, NULL, NULL, '["podcast"]'::jsonb, '[]'::jsonb, $$Lifestyle/contextual discovery.$$ , 1630),
  ($$mély interjú híres emberrel$$, $$mood_situation$$, $$topic$$, NULL, NULL, '["interjú"]'::jsonb, '[]'::jsonb, $$Format intent query.$$ , 1640),
  ($$rövid epizód hírekről$$, $$mood_situation$$, $$news$$, NULL, NULL, '["hír"]'::jsonb, '[]'::jsonb, $$Format plus freshness intent.$$ , 1650),
  ($$miért csuklik a gyerekem$$, $$natural_question$$, $$question$$, NULL, NULL, '["csuklik", "gyerek"]'::jsonb, '[]'::jsonb, $$Natural-language health/parenting question.$$ , 1710),
  ($$hogyan fektessek állampapírba$$, $$natural_question$$, $$question$$, NULL, NULL, '["állampapír"]'::jsonb, '[]'::jsonb, $$Natural-language finance question.$$ , 1720),
  ($$mi történik a forinttal$$, $$natural_question$$, $$question$$, NULL, NULL, '["forint"]'::jsonb, '[]'::jsonb, $$Natural-language economy question.$$ , 1730),
  ($$hogyan beszéljek a gyerekkel a válásról$$, $$natural_question$$, $$question$$, NULL, NULL, '["gyerek", "válás"]'::jsonb, '[]'::jsonb, $$Long natural-language family question.$$ , 1740),
  ($$milyen podcast szól a mesterséges intelligenciáról$$, $$natural_question$$, $$question$$, NULL, NULL, '["mesterséges", "intelligencia"]'::jsonb, '[]'::jsonb, $$Natural-language discovery question.$$ , 1750)
)
INSERT INTO public.search_golden_queries (
  query, query_type, expected_intent, expected_podcast_slug, expected_entity,
  must_include, must_exclude, notes, active, sort_order, updated_at
)
SELECT
  query, query_type, expected_intent, expected_podcast_slug, expected_entity,
  must_include, must_exclude, notes, true, sort_order, now()
FROM rows
ON CONFLICT (query) DO UPDATE
SET query_type = EXCLUDED.query_type,
    expected_intent = EXCLUDED.expected_intent,
    expected_podcast_slug = EXCLUDED.expected_podcast_slug,
    expected_entity = EXCLUDED.expected_entity,
    must_include = EXCLUDED.must_include,
    must_exclude = EXCLUDED.must_exclude,
    notes = EXCLUDED.notes,
    active = true,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();