UPDATE podcasts p SET
  hosts = v.hosts,
  hosts_source = 'manual_excel',
  hosts_updated_at = now()
FROM (VALUES
  ('nem-futball-calcio', ARRAY['Mártha Bence','Baumstark Tibor']::text[]),
  ('popkult-csajok-sat-bbi-podcasts', ARRAY['Lepp Tünde','Hudácskó Brigitta']::text[]),
  ('the-big-picture', ARRAY['Sean Fennessey','Amanda Dobbins']::text[]),
  ('budapest-eklektik-tilos-r-di-podcast', ARRAY['Latorczai Balázs','Girincsi Fruzsina','Erdélyi András','Eklics Krisztián']::text[]),
  ('z-rtoszt-ly-podcast', ARRAY['Süni néni','Benedict','Isti','Charles']::text[]),
  ('this-is-hcd-human-centred-design-ux-service-design', ARRAY['Gerry Scullion']::text[]),
  ('7t-r-t-tilos-r-di-podcast', ARRAY['Vé Ügynök','dr. bzmg','DubSmile','Melyik Feri']::text[]),
  ('the-rest-is-entertainment', ARRAY['Richard Osman','Marina Hyde']::text[]),
  ('planet-taxi-other-side', ARRAY['Phelan','Sasa','Gémer Bácsi']::text[]),
  ('m-nika-szatszangok-podcast', ARRAY['Horváth Mónika']::text[]),
  ('experiencing-data-w-brian-t-o-neill', ARRAY['Brian T. O’Neill']::text[]),
  ('forma-llapot', ARRAY['Farkas Flóra']::text[]),
  ('zleti-angol-egy-cs-sze-k-v-mellett', ARRAY['Danyi Andrea']::text[]),
  ('amir-l-nem-besz-l-nk', ARRAY['Knapek Éva']::text[]),
  ('8-perc-bence', ARRAY['Szabó Gál Bence']::text[]),
  ('szaval-a-j-reg-csall-k-zi', ARRAY['Jakubík Jolán','Tekács Ervin','Gyulabátty']::text[]),
  ('bochkor', ARRAY['Bochkor Gábor']::text[]),
  ('s-boldogan-ltek', ARRAY['Dr. Kádár Annamária','Vörös István']::text[]),
  ('hold-after-hours', ARRAY['Balásy Zsolt','Szabó Balázs']::text[]),
  ('biblia-egy-v-alatt-podcast-f-bry-korn-l-p-sp-k-aty-val', ARRAY['Fábry Kornél']::text[]),
  ('p-dermentes', ARRAY['Viszkok Fruzsi']::text[]),
  ('telex-after', ARRAY['Sajó Dávid']::text[]),
  ('konkr-tan-r-nai-egonnal', ARRAY['Rónai Egon']::text[]),
  ('friderikusz-podcast', ARRAY['Friderikusz Sándor']::text[]),
  ('biznisz-boyz-a-magyar-v-llalkoz-i-podcast-show', ARRAY['Sándorfy Adrián','Pál Zoli']::text[]),
  ('minner-podcast', ARRAY['Mándó Milán']::text[]),
  ('puzs-r-r-bert', ARRAY['Puzsér Róbert']::text[]),
  ('forex-t-zsde-hogyan-tr-delj', ARRAY['Várkuti Géza','Polyánszky Attila']::text[]),
  ('kontextus', ARRAY['Megadja Gábor','Hortay Olivér']::text[]),
  ('pogi-podcast', ARRAY['Pogátsa Zoltán']::text[]),
  ('neked-ugatok', ARRAY['Korom Gábor']::text[]),
  ('tears-of-jordan', ARRAY['Esperes Ákos','Rózsa Dávid']::text[]),
  ('thevr-happy-hour', ARRAY['Jani','Pisti']::text[]),
  ('l-r-stud-k', ARRAY['Szabó T. Anna']::text[]),
  ('nk-nyes-m-rvad-spirit-fm', ARRAY['Puzsér Róbert','Horváth Oszkár']::text[]),
  ('stepback-bazsk-val', ARRAY['Tőrös Balázs']::text[]),
  ('wmn-popfilter', ARRAY['Csepelyi Adrienn']::text[]),
  ('h-z-s', ARRAY['Rónai Egon']::text[]),
  ('90-9-jazzy-r-di-happy-hours', ARRAY['Jazzkovács László']::text[]),
  ('bal-zs-k', ARRAY['Sebestyén Balázs','Rákóczi Ferenc','Ráskó Eszter']::text[]),
  ('biblia-elvitelre', ARRAY['Nyári Attila']::text[]),
  ('frontvonal', ARRAY['Tarjányi Péter']::text[]),
  ('embereml-kezet', ARRAY['Horváth Szilárd']::text[]),
  ('keleten-nyugaton-podcast', ARRAY['Rédai Gábor','Zukály Zoltán']::text[]),
  ('szavakon-t-l', ARRAY['Kadarkai Endre']::text[]),
  ('csak-l-nk-s-mes-l-nk', ARRAY['Forgács W András','Laska Pál','Mester Ákos']::text[]),
  ('fel-t-s-zenei-podcast', ARRAY['György Imre','Jacsó Miklós']::text[]),
  ('k-osz-podcast-miskovits-marcival', ARRAY['Miskovits Marci']::text[]),
  ('hiteles-jogi-tan-csok', ARRAY['Dr. Nagy Zsuzsanna']::text[]),
  ('gondolat-breszt', ARRAY['Jantek Gyöngyvér','Király Kinga']::text[]),
  ('bet-t-szta', ARRAY['Dömötör László']::text[]),
  ('rossznyavalya-ostroma-podcast', ARRAY['Dzé','Mr. Jackpot']::text[]),
  ('2020-filmod-sszeia', ARRAY['Oxi','Dávid']::text[]),
  ('asztro-podcast', ARRAY['Oláhné Mednyánszki Krisztina']::text[]),
  ('blikk-gy-z-dum-ljuk-meg', ARRAY['Szabó Győző']::text[]),
  ('szabades-s', ARRAY['Marosi Viktor']::text[]),
  ('az-n-k-k-z-n-m', ARRAY['Hámori Barbara']::text[]),
  ('biri-bal-zs-podcast', ARRAY['Biri Balázs']::text[]),
  ('magyar-filmek-t-l-cettig', ARRAY['Bonta Luca','Török Ádám']::text[]),
  ('lt-egyszer-egy-olvas', ARRAY['Mészáros Márton','Neszlár Sándor']::text[]),
  ('class-fm-best-morning-show-in-hungary', ARRAY['Sebestyén Balázs','Rákóczi Ferenc','Vadon János']::text[]),
  ('p-ntek-reggel', ARRAY['Szurovecz Illés']::text[]),
  ('csillagvizsg-l', ARRAY['Barna Barnabás','Ordasi András']::text[]),
  ('az-ingatlanos-podcast-mlin-rik-m-rton', ARRAY['Mlinárik Márton']::text[]),
  ('americast', ARRAY['Horváth Dániel','Nabil']::text[]),
  ('l-lek-koffein-podcast', ARRAY['Pauer Krisztina']::text[]),
  ('semmi-komoly-h-mori-m-t-podcastja', ARRAY['Hámori Máté']::text[]),
  ('hekt-r-mez-gazdas-gi-podcast', ARRAY['Gribek Dani']::text[]),
  ('sport-motiv-tor', ARRAY['Gajdos Tamás']::text[]),
  ('kem-ny-id-k', ARRAY['Wostry Ferenc']::text[]),
  ('felforgat-k', ARRAY['Kadarkai Endre']::text[]),
  ('a-holnap-tegnapja', ARRAY['Nyul Zsuzsa']::text[]),
  ('wmn-besz-ln-nk-kell', ARRAY['D. Tóth Kriszta','Orvos-Tóth Noémi']::text[]),
  ('holonet-kr-nik-k', ARRAY['Horváth Ede']::text[]),
  ('meghallgatunk-online-mental-health-podcast', ARRAY['Gilányi Attila']::text[]),
  ('az-let-meg-minden', ARRAY['Tóth Szabolcs Töhötöm']::text[]),
  ('fem-fiction-k-nyves-podcast', ARRAY['Sári','Panni','Niki']::text[]),
  ('p-csi-panthers-podcast', ARRAY['László Miklós','Szakács Miklós']::text[]),
  ('bel-p-si-k-sz-b', ARRAY['Schultz Nóra']::text[]),
  ('p-r-perc-mese', ARRAY['Horváth Bernadett']::text[]),
  ('global-news-podcast', ARRAY['Nógrádi György']::text[]),
  ('a-m-p-a-makettez-podcast', ARRAY['Alberti Dániel','Nagy-Meszler Csaba']::text[]),
  ('sz-ljegyzetek-s-rosi-p-ter-podcastja', ARRAY['Sárosi Péter']::text[]),
  ('kutya1-gy', ARRAY['Borbély Zsuzsa']::text[]),
  ('bridgestone-archives-mill-sreggeli-a-gazdas-gi-muppet-show', ARRAY['Ács Gábor','Gede Balázs','Kántor Endre','Mihálovits András']::text[]),
  ('mill-sreggeli-a-gazdas-gi-muppet-show', ARRAY['Ács Gábor','Gede Balázs','Kántor Endre','Mihálovits András']::text[]),
  ('checkpoint', ARRAY['Grath','Stöki']::text[]),
  ('tudatos-podcast', ARRAY['Bagi Renáta']::text[]),
  ('anyasztori-gyerekkelvagyok-besz-des-henrietta-m-sora', ARRAY['Beszédes Henrietta']::text[]),
  ('tan-t-sok-gy-gyul-s-hangja-kereszt-ny-misszi', ARRAY['Magyari László']::text[]),
  ('adom-az-arcom-podcast-t-th-bal-zzsal', ARRAY['Tóth Balázs']::text[]),
  ('alley-oop-2', ARRAY['Szaniszló Csaba','Tőrös Balázs']::text[]),
  ('flash-crash-archives-mill-sreggeli-a-gazdas-gi-muppet-show', ARRAY['Ács Gábor','Gede Balázs','Kántor Endre','Mihálovits András']::text[]),
  ('itt-vagyok-let-s-eg-szs-g-podcast-b-nhalmi-kat-val', ARRAY['Bánhalmi Kata']::text[]),
  ('eleg-ns-t-n-d-s', ARRAY['Lovasi András']::text[]),
  ('t-bb-kevesebb', ARRAY['Rónai Egon']::text[]),
  ('berencsi-bal-zs-podcast', ARRAY['Berencsi Balázs']::text[]),
  ('erotika-archives-mill-sreggeli-a-gazdas-gi-muppet-show', ARRAY['Ács Gábor','Gede Balázs','Kántor Endre','Mihálovits András']::text[]),
  ('gazd-b-l-v-llalkoz-i-morvan-v-nydoki', ARRAY['Morva Növénydoki','Gál Kristóf']::text[]),
  ('sz-zhold-veiszer-alind-val', ARRAY['Veiszer Alinda']::text[]),
  ('r-kam-j-bors-rich-rddal', ARRAY['Bors Richárd']::text[]),
  ('ing-tempo-t-nyek-elemz-sek-makrogazdas-g-podcast', ARRAY['Virovácz Péter']::text[]),
  ('apu-az-rt-iszik-mert-te-s-rsz', ARRAY['Puzsér Róbert','Farkas Attila Márton']::text[]),
  ('ayahuasca', ARRAY['Noémi']::text[]),
  ('alley-oop-1', ARRAY['Szaniszló Csaba','Tőrös Balázs']::text[]),
  ('dr-balsai-tam-s-s-a-perfect-smile-fog-szat-csapat-nak-hivatalos-podcast-csatorn-', ARRAY['Dr. Balsai Tamás']::text[]),
  ('v-ltoz-s-k-v-h-z', ARRAY['Gillich-Csikós Andrea Judit']::text[]),
  ('h-rmasban', ARRAY['Várkonyi Gábor']::text[]),
  ('a-jelen-sek-k-nyve-pr-f-ci-i-korunkra-n-zve', ARRAY['Dr. Vankó Zsuzsa']::text[]),
  ('vet', ARRAY['Vető Balázs']::text[]),
  ('hat-skelt-k-l-ferkai-marcell-m-sora', ARRAY['Ferkai Marcell']::text[]),
  ('ciklusom', ARRAY['Lilla']::text[]),
  ('serb-n-adam-s-show', ARRAY['Serbán Adam']::text[]),
  ('g-nczi-j-zsef-s-show', ARRAY['Gönczi József']::text[]),
  ('attila-sebesty-n-s-podcast', ARRAY['Attila Sebestyén']::text[]),
  ('istv-n-ofcs-k-s-show', ARRAY['István Ofcsák']::text[]),
  ('alley-oop', ARRAY['Szaniszló Csaba','Tőrös Balázs']::text[]),
  ('podcastepiz-dok-az-let-meg-minden', ARRAY['Tóth Szabolcs Töhötöm']::text[]),
  ('b-leczki-n-ra-s-podcast', ARRAY['Béleczki Nóra']::text[]),
  ('levente-m-t-hajdu-s-show', ARRAY['Levente Máté Hajdu']::text[]),
  ('skociaimagyarok', ARRAY['Betty','László']::text[]),
  ('robert-rajo-s-podcast', ARRAY['Robert Rajo']::text[]),
  ('pole-poz-ci-podcast-szuj-zolt-nnal', ARRAY['Szujó Zoltán']::text[]),
  ('laciikaa-pocz-k-gino-s-show', ARRAY['Laciikaa Poczók Gino']::text[]),
  ('klikk-out-filmes', ARRAY['Tóth Lali','Fuji Peti']::text[])
) AS v(slug, hosts)
WHERE p.slug = v.slug;